version: '3.8'

services:
  app:
    image: stas_calc_serv:latest  # Указываем имя образа
    container_name: stas_calc_serv
    ports:
      - "5002:5002"  
    env_file:
      - .env  # Указываем файл с переменными среды
    restart: unless-stopped

  